spring:
  datasource:
    username: ShaoBin
    password: a88675577
    url: jdbc:mysql://localhost:3306/BadgerMarket?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
  img:
    itemimageUrl: file:/Users/shaobindanielhong/MyProject/BadgerMarket/webBackEnd/src/main/resources/static/